version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3305:3305

  psql:
    container_name: psql
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: psql_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
