version: '3'
services:
  pcs-backend:
    depends_on:
      - psql
    build:
      context: .
      dockerfile: src/app/Dockerfile
    env_file:
      - .env
    container_name: pcs-backend
    image: registry.heroku.com/backend-2102/web
    environment:
      ENV: "dev"
      NODE_ENV: "production"
      PORT: "${PORT}"
      DB_HOST: psql
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "8080:${PORT}"

  psql:
    env_file:
      - .env
    container_name: psql
    image: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "54321:${DB_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${DB_HOST}:${DB_PORT}"]
      interval: 10s
      timeout: 10s
      retries: 5
