version: '3'
services:
  pcs-backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: pcs-backend
    image: t00102546823/pcs-backend
    environment:
      ENV: "dev"
      NODE_ENV: "production"
      PORT: 8081
      HOST: 0.0.0.0
      WDS_SOCKET_HOST: 0.0.0.0
      DB_HOST: psql
      DB_PORT: 5432
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 9090:9090
      - 9901:9901
      - 3000:8080
      - 8081:8081

  psql:
    env_file:
      - .env
    container_name: psql
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 54321:5432
