version: '3'
services:
  pcs-backend:
    build:
      context: .
      dockerfile: src/app/Dockerfile
    env_file:
      - .env
    container_name: pcs-backend
    image: registry.heroku.com/backend-2102/web
    environment:
      ENV: "dev"
      NODE_ENV: "production"
      PORT: 8080
      DB_HOST: psql
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - 8080:8080

  psql:
    env_file:
      - .env
    container_name: psql
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 54321:5432
