version: '3'
services:
  pcs-backend:
    build:
      context: .
      dockerfile: src/app/Dockerfile
    env_file:
      - .env
    container_name: pcs-backend
    environment:
      ENV: "dev"
      PORT: 8080
      DB_HOST: psql
      DB_PORT: 5432
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 8080:8080

  pcs-frontend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: src/webapp/Dockerfile
    container_name: pcs-frontend
    environment:
      NODE_ENV: production
      PORT: 4000
      ENV: "dev"
    ports:
      - 5000:4000
    stdin_open: true

  psql:
    env_file:
      - .env
    container_name: psql
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 54321:5432
