version: '3'
services:
  pcs-backend:
    env_file:
      - .env
    build: .
    container_name: pcs-backend
    image: t00102546823/pcs-backend
    environment:
      PORT: 8080
      DB_HOST: psql
      DB_PORT: 5432
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 9090:9090
      - "${PORT}:8080"

  psql:
    env_file:
      - .env
    container_name: psql
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 5432:5432
