INSERT INTO public.categories (name, parent, price) VALUES ('Fox, crab-eating', null, 1);
INSERT INTO public.categories (name, parent, price) VALUES ('Superb starling', null, 1);
INSERT INTO public.categories (name, parent, price) VALUES ('American black bear', null, 1);
INSERT INTO public.categories (name, parent, price) VALUES ('Vine snake (unidentified)', null, 1);
INSERT INTO public.categories (name, parent, price) VALUES ('Hyena, brown', null, 1);
INSERT INTO public.categories (name, parent, price) VALUES ('Stanley bustard', null, 1);
INSERT INTO public.categories (name, parent, price) VALUES ('Javan gold-spotted mongoose', null, 1);
INSERT INTO public.categories (name, parent, price) VALUES ('Mouse, four-striped grass', null, 1);
INSERT INTO public.categories (name, parent, price) VALUES ('Spectacled caiman', null, 1);
INSERT INTO public.categories (name, parent, price) VALUES ('Painted stork', null, 1);
INSERT INTO public.categories (name, parent, price) VALUES ('Dog', null, 1);