INSERT INTO public.min_daily_prices (category, price) VALUES ('Fox, crab-eating', 4);
INSERT INTO public.min_daily_prices (category, price) VALUES ('Superb starling', 4);
INSERT INTO public.min_daily_prices (category, price) VALUES ('American black bear', 5);
INSERT INTO public.min_daily_prices (category, price) VALUES ('Vine snake (unidentified)', 4);
INSERT INTO public.min_daily_prices (category, price) VALUES ('Hyena, brown', 4);
INSERT INTO public.min_daily_prices (category, price) VALUES ('Stanley bustard', 4);
INSERT INTO public.min_daily_prices (category, price) VALUES ('Javan gold-spotted mongoose', 4);
INSERT INTO public.min_daily_prices (category, price) VALUES ('Mouse, four-striped grass', 4);
INSERT INTO public.min_daily_prices (category, price) VALUES ('Spectacled caiman', 4);
INSERT INTO public.min_daily_prices (category, price) VALUES ('Painted stork', 5);