INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cocallaghan0@linkedin.com', 'Vulture, griffon', 6549);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cocallaghan0@linkedin.com', 'Gull, lava', 9766);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cocallaghan0@linkedin.com', 'Whale, killer', 8215);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cocallaghan0@linkedin.com', 'Red-winged blackbird', 8812);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cocallaghan0@linkedin.com', 'Monkey, red howler', 8187);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dtabbernor1@weebly.com', 'Savannah deer (unidentified)', 7597);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dtabbernor1@weebly.com', 'Asiatic jackal', 9024);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dtabbernor1@weebly.com', 'Whale, killer', 9154);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dtabbernor1@weebly.com', 'Monkey, red howler', 8503);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('livankin2@google.cn', 'Vulture, griffon', 5708);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('livankin2@google.cn', 'Gull, lava', 9521);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('livankin2@google.cn', 'Asiatic jackal', 8712);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('livankin2@google.cn', 'Whale, killer', 6309);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('livankin2@google.cn', 'Monkey, red howler', 7736);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('livankin2@google.cn', 'Galapagos penguin', 8884);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('velmer3@google.es', 'Vulture, griffon', 6355);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('velmer3@google.es', 'Savannah deer (unidentified)', 8240);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('velmer3@google.es', 'Asiatic jackal', 8097);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('velmer3@google.es', 'Whale, killer', 9514);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('velmer3@google.es', 'Red-winged blackbird', 9613);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('velmer3@google.es', 'Monkey, red howler', 8540);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('velmer3@google.es', 'Cobra, egyptian', 9047);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lbilham4@mozilla.com', 'Vulture, griffon', 8198);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lbilham4@mozilla.com', 'Gull, lava', 7295);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lbilham4@mozilla.com', 'Asiatic jackal', 9298);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lbilham4@mozilla.com', 'Bohor reedbuck', 9835);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lbilham4@mozilla.com', 'Monkey, red howler', 9518);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lbilham4@mozilla.com', 'Cobra, egyptian', 7817);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cwestwood5@hc360.com', 'Vulture, griffon', 7218);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cwestwood5@hc360.com', 'Savannah deer (unidentified)', 7888);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cwestwood5@hc360.com', 'Asiatic jackal', 8781);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cwestwood5@hc360.com', 'Whale, killer', 7728);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cwestwood5@hc360.com', 'Galapagos penguin', 9730);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('eoldfield6@telegraph.co.uk', 'Vulture, griffon', 5654);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('eoldfield6@telegraph.co.uk', 'Gull, lava', 9237);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('eoldfield6@telegraph.co.uk', 'Asiatic jackal', 9167);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('eoldfield6@telegraph.co.uk', 'Whale, killer', 8813);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('eoldfield6@telegraph.co.uk', 'Monkey, red howler', 8117);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('eoldfield6@telegraph.co.uk', 'Cobra, egyptian', 8842);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('abalassa7@thetimes.co.uk', 'Vulture, griffon', 8193);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('abalassa7@thetimes.co.uk', 'Gull, lava', 7813);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('abalassa7@thetimes.co.uk', 'Asiatic jackal', 9181);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('abalassa7@thetimes.co.uk', 'Whale, killer', 6610);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('abalassa7@thetimes.co.uk', 'Red-winged blackbird', 9855);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('abalassa7@thetimes.co.uk', 'Monkey, red howler', 6294);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('abalassa7@thetimes.co.uk', 'Galapagos penguin', 9892);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('abalassa7@thetimes.co.uk', 'Cobra, egyptian', 8068);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('vbeech8@addthis.com', 'Vulture, griffon', 6484);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('vbeech8@addthis.com', 'Gull, lava', 8185);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('vbeech8@addthis.com', 'Asiatic jackal', 7813);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('vbeech8@addthis.com', 'Whale, killer', 7230);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('vbeech8@addthis.com', 'Monkey, red howler', 5279);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('vbeech8@addthis.com', 'Galapagos penguin', 9379);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('vbeech8@addthis.com', 'Cobra, egyptian', 9032);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ezannetti9@webs.com', 'Vulture, griffon', 7432);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ezannetti9@webs.com', 'Savannah deer (unidentified)', 7627);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ezannetti9@webs.com', 'Gull, lava', 8000);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ezannetti9@webs.com', 'Asiatic jackal', 8510);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ezannetti9@webs.com', 'Whale, killer', 7672);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ezannetti9@webs.com', 'Red-winged blackbird', 9188);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ezannetti9@webs.com', 'Monkey, red howler', 9725);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ezannetti9@webs.com', 'Galapagos penguin', 8875);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ezannetti9@webs.com', 'Cobra, egyptian', 7738);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ebeehoa@msn.com', 'Vulture, griffon', 6439);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ebeehoa@msn.com', 'Savannah deer (unidentified)', 9518);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ebeehoa@msn.com', 'Gull, lava', 9475);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ebeehoa@msn.com', 'Asiatic jackal', 7956);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ebeehoa@msn.com', 'Whale, killer', 6303);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ebeehoa@msn.com', 'Red-winged blackbird', 8864);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ebeehoa@msn.com', 'Monkey, red howler', 7984);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ebeehoa@msn.com', 'Cobra, egyptian', 9508);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ncarenb@prnewswire.com', 'Vulture, griffon', 7622);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ncarenb@prnewswire.com', 'Asiatic jackal', 9732);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ncarenb@prnewswire.com', 'Bohor reedbuck', 9146);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ncarenb@prnewswire.com', 'Whale, killer', 7043);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ncarenb@prnewswire.com', 'Monkey, red howler', 7840);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ncarenb@prnewswire.com', 'Cobra, egyptian', 8079);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gmcmahonc@usnews.com', 'Vulture, griffon', 8702);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gmcmahonc@usnews.com', 'Savannah deer (unidentified)', 8470);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gmcmahonc@usnews.com', 'Gull, lava', 8212);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gmcmahonc@usnews.com', 'Whale, killer', 6392);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gmcmahonc@usnews.com', 'Red-winged blackbird', 8630);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gmcmahonc@usnews.com', 'Monkey, red howler', 9768);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gmcmahonc@usnews.com', 'Galapagos penguin', 9093);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gmcmahonc@usnews.com', 'Cobra, egyptian', 7808);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ggreenoughd@free.fr', 'Vulture, griffon', 5655);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ggreenoughd@free.fr', 'Gull, lava', 9826);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ggreenoughd@free.fr', 'Asiatic jackal', 8742);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ggreenoughd@free.fr', 'Bohor reedbuck', 9513);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ggreenoughd@free.fr', 'Whale, killer', 9455);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ggreenoughd@free.fr', 'Red-winged blackbird', 7920);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ggreenoughd@free.fr', 'Monkey, red howler', 5502);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ggreenoughd@free.fr', 'Galapagos penguin', 9581);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ereallye@nasa.gov', 'Vulture, griffon', 7279);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ereallye@nasa.gov', 'Asiatic jackal', 7554);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ereallye@nasa.gov', 'Whale, killer', 6386);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ereallye@nasa.gov', 'Monkey, red howler', 7783);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('emcgivenf@bloglovin.com', 'Vulture, griffon', 7381);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('emcgivenf@bloglovin.com', 'Savannah deer (unidentified)', 8415);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('emcgivenf@bloglovin.com', 'Gull, lava', 9059);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('emcgivenf@bloglovin.com', 'Asiatic jackal', 7490);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('emcgivenf@bloglovin.com', 'Bohor reedbuck', 9475);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('emcgivenf@bloglovin.com', 'Monkey, red howler', 6763);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gmangamg@wisc.edu', 'Gull, lava', 9756);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gmangamg@wisc.edu', 'Asiatic jackal', 6924);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gmangamg@wisc.edu', 'Whale, killer', 6901);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gmangamg@wisc.edu', 'Red-winged blackbird', 9772);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gmangamg@wisc.edu', 'Monkey, red howler', 5429);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gmangamg@wisc.edu', 'Cobra, egyptian', 9458);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('csinkinsonh@cyberchimps.com', 'Vulture, griffon', 9647);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('csinkinsonh@cyberchimps.com', 'Gull, lava', 9455);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('csinkinsonh@cyberchimps.com', 'Asiatic jackal', 7644);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('csinkinsonh@cyberchimps.com', 'Bohor reedbuck', 9495);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('csinkinsonh@cyberchimps.com', 'Whale, killer', 9471);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('csinkinsonh@cyberchimps.com', 'Red-winged blackbird', 8818);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('csinkinsonh@cyberchimps.com', 'Monkey, red howler', 9577);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ranani@nifty.com', 'Vulture, griffon', 9595);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ranani@nifty.com', 'Savannah deer (unidentified)', 9172);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ranani@nifty.com', 'Asiatic jackal', 7415);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ranani@nifty.com', 'Whale, killer', 9105);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ranani@nifty.com', 'Red-winged blackbird', 9828);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ranani@nifty.com', 'Monkey, red howler', 5676);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ranani@nifty.com', 'Cobra, egyptian', 7809);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('imacellarj@wix.com', 'Vulture, griffon', 5955);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('imacellarj@wix.com', 'Savannah deer (unidentified)', 9850);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('imacellarj@wix.com', 'Bohor reedbuck', 9265);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('imacellarj@wix.com', 'Whale, killer', 9201);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('imacellarj@wix.com', 'Monkey, red howler', 6025);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('nmolnark@indiegogo.com', 'Savannah deer (unidentified)', 9330);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('nmolnark@indiegogo.com', 'Asiatic jackal', 8519);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('nmolnark@indiegogo.com', 'Whale, killer', 8928);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('nmolnark@indiegogo.com', 'Monkey, red howler', 9277);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fduchaml@globo.com', 'Vulture, griffon', 9549);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fduchaml@globo.com', 'Savannah deer (unidentified)', 8484);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fduchaml@globo.com', 'Gull, lava', 9125);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fduchaml@globo.com', 'Asiatic jackal', 9317);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fduchaml@globo.com', 'Whale, killer', 7599);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fduchaml@globo.com', 'Monkey, red howler', 6985);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('agouthm@so-net.ne.jp', 'Vulture, griffon', 8904);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('agouthm@so-net.ne.jp', 'Savannah deer (unidentified)', 8058);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('agouthm@so-net.ne.jp', 'Bohor reedbuck', 9656);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('agouthm@so-net.ne.jp', 'Monkey, red howler', 7073);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('agouthm@so-net.ne.jp', 'Galapagos penguin', 9736);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fmelarkeyn@amazonaws.com', 'Vulture, griffon', 7245);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fmelarkeyn@amazonaws.com', 'Savannah deer (unidentified)', 7276);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fmelarkeyn@amazonaws.com', 'Gull, lava', 7269);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fmelarkeyn@amazonaws.com', 'Asiatic jackal', 9027);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fmelarkeyn@amazonaws.com', 'Whale, killer', 8753);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fmelarkeyn@amazonaws.com', 'Monkey, red howler', 5161);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fmelarkeyn@amazonaws.com', 'Galapagos penguin', 9478);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fmelarkeyn@amazonaws.com', 'Cobra, egyptian', 8630);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('baronso@cbc.ca', 'Vulture, griffon', 7990);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('baronso@cbc.ca', 'Savannah deer (unidentified)', 7889);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('baronso@cbc.ca', 'Asiatic jackal', 8120);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('baronso@cbc.ca', 'Whale, killer', 9368);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('baronso@cbc.ca', 'Red-winged blackbird', 8333);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('baronso@cbc.ca', 'Monkey, red howler', 8180);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('baronso@cbc.ca', 'Galapagos penguin', 8656);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('kformanp@cam.ac.uk', 'Vulture, griffon', 9566);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('kformanp@cam.ac.uk', 'Savannah deer (unidentified)', 8201);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('kformanp@cam.ac.uk', 'Asiatic jackal', 6808);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('kformanp@cam.ac.uk', 'Whale, killer', 8839);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('kformanp@cam.ac.uk', 'Monkey, red howler', 6372);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('kformanp@cam.ac.uk', 'Cobra, egyptian', 8051);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dbagotq@1688.com', 'Asiatic jackal', 6934);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dbagotq@1688.com', 'Red-winged blackbird', 9838);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dbagotq@1688.com', 'Monkey, red howler', 6602);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dbagotq@1688.com', 'Cobra, egyptian', 8204);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('tromerilr@cbslocal.com', 'Vulture, griffon', 8301);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('tromerilr@cbslocal.com', 'Savannah deer (unidentified)', 8979);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('tromerilr@cbslocal.com', 'Gull, lava', 8179);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('tromerilr@cbslocal.com', 'Asiatic jackal', 7278);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('tromerilr@cbslocal.com', 'Whale, killer', 7449);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('tromerilr@cbslocal.com', 'Red-winged blackbird', 8414);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('tromerilr@cbslocal.com', 'Monkey, red howler', 9990);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('tromerilr@cbslocal.com', 'Cobra, egyptian', 9944);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mchicchellis@slideshare.net', 'Vulture, griffon', 7420);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mchicchellis@slideshare.net', 'Gull, lava', 7141);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mchicchellis@slideshare.net', 'Bohor reedbuck', 9948);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mchicchellis@slideshare.net', 'Red-winged blackbird', 8641);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mchicchellis@slideshare.net', 'Monkey, red howler', 9925);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mchicchellis@slideshare.net', 'Galapagos penguin', 9878);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('bveitcht@smh.com.au', 'Vulture, griffon', 7918);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('bveitcht@smh.com.au', 'Savannah deer (unidentified)', 9896);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('bveitcht@smh.com.au', 'Gull, lava', 7508);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('bveitcht@smh.com.au', 'Bohor reedbuck', 9913);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('bveitcht@smh.com.au', 'Whale, killer', 6482);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('bveitcht@smh.com.au', 'Red-winged blackbird', 8032);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('bveitcht@smh.com.au', 'Monkey, red howler', 9277);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lscotchmuru@tuttocitta.it', 'Vulture, griffon', 6292);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lscotchmuru@tuttocitta.it', 'Savannah deer (unidentified)', 9145);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lscotchmuru@tuttocitta.it', 'Whale, killer', 7041);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lscotchmuru@tuttocitta.it', 'Red-winged blackbird', 8019);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lscotchmuru@tuttocitta.it', 'Monkey, red howler', 5935);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lscotchmuru@tuttocitta.it', 'Cobra, egyptian', 8248);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lbohmanv@behance.net', 'Vulture, griffon', 6124);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lbohmanv@behance.net', 'Savannah deer (unidentified)', 9170);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lbohmanv@behance.net', 'Asiatic jackal', 7949);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lbohmanv@behance.net', 'Whale, killer', 8119);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lbohmanv@behance.net', 'Monkey, red howler', 8665);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lbohmanv@behance.net', 'Cobra, egyptian', 9243);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ddawberw@vimeo.com', 'Vulture, griffon', 6175);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ddawberw@vimeo.com', 'Asiatic jackal', 8096);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ddawberw@vimeo.com', 'Whale, killer', 8756);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ddawberw@vimeo.com', 'Monkey, red howler', 7761);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ddawberw@vimeo.com', 'Galapagos penguin', 9281);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lstormsx@ebay.co.uk', 'Vulture, griffon', 9240);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lstormsx@ebay.co.uk', 'Savannah deer (unidentified)', 7780);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lstormsx@ebay.co.uk', 'Bohor reedbuck', 8830);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lstormsx@ebay.co.uk', 'Monkey, red howler', 9308);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lstormsx@ebay.co.uk', 'Cobra, egyptian', 9309);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('sjermyy@nba.com', 'Vulture, griffon', 7718);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('sjermyy@nba.com', 'Savannah deer (unidentified)', 9715);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('sjermyy@nba.com', 'Gull, lava', 7145);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('sjermyy@nba.com', 'Whale, killer', 9095);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('sjermyy@nba.com', 'Red-winged blackbird', 8988);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('sjermyy@nba.com', 'Monkey, red howler', 5823);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('sjermyy@nba.com', 'Cobra, egyptian', 9661);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('wcamidgez@51.la', 'Vulture, griffon', 9683);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('wcamidgez@51.la', 'Savannah deer (unidentified)', 9403);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('wcamidgez@51.la', 'Gull, lava', 7765);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('wcamidgez@51.la', 'Red-winged blackbird', 9890);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('wcamidgez@51.la', 'Monkey, red howler', 6701);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('wcamidgez@51.la', 'Cobra, egyptian', 9145);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('wbeeby10@mlb.com', 'Vulture, griffon', 9561);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('wbeeby10@mlb.com', 'Savannah deer (unidentified)', 7582);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('wbeeby10@mlb.com', 'Asiatic jackal', 7343);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('wbeeby10@mlb.com', 'Bohor reedbuck', 9994);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('wbeeby10@mlb.com', 'Whale, killer', 8123);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('wbeeby10@mlb.com', 'Red-winged blackbird', 8849);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('wbeeby10@mlb.com', 'Monkey, red howler', 8297);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('wbeeby10@mlb.com', 'Cobra, egyptian', 9426);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('amewburn11@infoseek.co.jp', 'Vulture, griffon', 6284);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('amewburn11@infoseek.co.jp', 'Gull, lava', 8461);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('amewburn11@infoseek.co.jp', 'Bohor reedbuck', 9730);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('amewburn11@infoseek.co.jp', 'Whale, killer', 7844);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('amewburn11@infoseek.co.jp', 'Red-winged blackbird', 9212);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('amewburn11@infoseek.co.jp', 'Monkey, red howler', 5423);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('amewburn11@infoseek.co.jp', 'Cobra, egyptian', 9539);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cphilipp12@bbb.org', 'Vulture, griffon', 6740);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cphilipp12@bbb.org', 'Asiatic jackal', 8250);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cphilipp12@bbb.org', 'Whale, killer', 9551);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cphilipp12@bbb.org', 'Red-winged blackbird', 9915);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cphilipp12@bbb.org', 'Monkey, red howler', 6112);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cphilipp12@bbb.org', 'Galapagos penguin', 9599);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fbaggaley13@ed.gov', 'Savannah deer (unidentified)', 8157);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fbaggaley13@ed.gov', 'Bohor reedbuck', 9897);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fbaggaley13@ed.gov', 'Whale, killer', 8587);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fbaggaley13@ed.gov', 'Red-winged blackbird', 9290);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fbaggaley13@ed.gov', 'Monkey, red howler', 5893);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('aerrey14@yellowpages.com', 'Asiatic jackal', 9266);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('aerrey14@yellowpages.com', 'Whale, killer', 9109);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('aerrey14@yellowpages.com', 'Monkey, red howler', 7050);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('wsaenz15@themeforest.net', 'Savannah deer (unidentified)', 9184);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('wsaenz15@themeforest.net', 'Asiatic jackal', 8500);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('wsaenz15@themeforest.net', 'Whale, killer', 7450);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('wsaenz15@themeforest.net', 'Monkey, red howler', 6827);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('wsaenz15@themeforest.net', 'Cobra, egyptian', 9681);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mbrace16@amazon.de', 'Vulture, griffon', 8666);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mbrace16@amazon.de', 'Savannah deer (unidentified)', 7645);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mbrace16@amazon.de', 'Gull, lava', 7210);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mbrace16@amazon.de', 'Asiatic jackal', 8502);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mbrace16@amazon.de', 'Whale, killer', 8197);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mbrace16@amazon.de', 'Red-winged blackbird', 9602);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mbrace16@amazon.de', 'Monkey, red howler', 9282);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mbrace16@amazon.de', 'Cobra, egyptian', 8485);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('nmulles17@blinklist.com', 'Vulture, griffon', 9878);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('nmulles17@blinklist.com', 'Gull, lava', 9721);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('nmulles17@blinklist.com', 'Asiatic jackal', 9522);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('nmulles17@blinklist.com', 'Whale, killer', 7575);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('nmulles17@blinklist.com', 'Red-winged blackbird', 9632);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('nmulles17@blinklist.com', 'Monkey, red howler', 8520);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('nmulles17@blinklist.com', 'Cobra, egyptian', 7702);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('crudinger18@microsoft.com', 'Vulture, griffon', 9981);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('crudinger18@microsoft.com', 'Savannah deer (unidentified)', 9454);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('crudinger18@microsoft.com', 'Whale, killer', 7485);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('crudinger18@microsoft.com', 'Red-winged blackbird', 8591);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('crudinger18@microsoft.com', 'Monkey, red howler', 5930);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('crudinger18@microsoft.com', 'Cobra, egyptian', 8823);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ekalinsky19@typepad.com', 'Vulture, griffon', 6630);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ekalinsky19@typepad.com', 'Whale, killer', 9562);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ekalinsky19@typepad.com', 'Red-winged blackbird', 9439);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ekalinsky19@typepad.com', 'Monkey, red howler', 8506);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lbartol1a@pcworld.com', 'Vulture, griffon', 7334);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lbartol1a@pcworld.com', 'Savannah deer (unidentified)', 8959);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lbartol1a@pcworld.com', 'Gull, lava', 9429);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lbartol1a@pcworld.com', 'Asiatic jackal', 8086);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lbartol1a@pcworld.com', 'Bohor reedbuck', 9905);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lbartol1a@pcworld.com', 'Whale, killer', 7346);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lbartol1a@pcworld.com', 'Monkey, red howler', 9718);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mrosgen1b@gizmodo.com', 'Vulture, griffon', 8470);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mrosgen1b@gizmodo.com', 'Asiatic jackal', 9500);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mrosgen1b@gizmodo.com', 'Whale, killer', 8636);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mrosgen1b@gizmodo.com', 'Red-winged blackbird', 9790);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mrosgen1b@gizmodo.com', 'Monkey, red howler', 7697);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mrosgen1b@gizmodo.com', 'Galapagos penguin', 9320);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cclunan1c@hibu.com', 'Vulture, griffon', 9559);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cclunan1c@hibu.com', 'Gull, lava', 9349);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cclunan1c@hibu.com', 'Asiatic jackal', 7495);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cclunan1c@hibu.com', 'Whale, killer', 9800);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cclunan1c@hibu.com', 'Red-winged blackbird', 7781);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cclunan1c@hibu.com', 'Monkey, red howler', 6295);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('omcshirrie1d@hostgator.com', 'Vulture, griffon', 6564);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('omcshirrie1d@hostgator.com', 'Savannah deer (unidentified)', 9273);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('omcshirrie1d@hostgator.com', 'Bohor reedbuck', 9513);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('omcshirrie1d@hostgator.com', 'Whale, killer', 7530);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('omcshirrie1d@hostgator.com', 'Red-winged blackbird', 8210);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('omcshirrie1d@hostgator.com', 'Monkey, red howler', 5947);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('bcowins1e@slate.com', 'Vulture, griffon', 8066);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('bcowins1e@slate.com', 'Savannah deer (unidentified)', 9409);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('bcowins1e@slate.com', 'Gull, lava', 7296);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('bcowins1e@slate.com', 'Asiatic jackal', 8987);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('bcowins1e@slate.com', 'Whale, killer', 8550);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('bcowins1e@slate.com', 'Monkey, red howler', 6898);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('bcowins1e@slate.com', 'Galapagos penguin', 9186);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('bcowins1e@slate.com', 'Cobra, egyptian', 8791);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('clindell1f@pcworld.com', 'Gull, lava', 9977);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('clindell1f@pcworld.com', 'Whale, killer', 7723);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('clindell1f@pcworld.com', 'Red-winged blackbird', 8585);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('clindell1f@pcworld.com', 'Monkey, red howler', 9998);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('pcosgrave1g@desdev.cn', 'Vulture, griffon', 8893);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('pcosgrave1g@desdev.cn', 'Savannah deer (unidentified)', 7782);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('pcosgrave1g@desdev.cn', 'Asiatic jackal', 9910);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('pcosgrave1g@desdev.cn', 'Whale, killer', 6758);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('pcosgrave1g@desdev.cn', 'Red-winged blackbird', 8775);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('pcosgrave1g@desdev.cn', 'Monkey, red howler', 6191);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('hseniour2e@skype.com', 'Whale, killer', 6866);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('agethyn1h@phpbb.com', 'Vulture, griffon', 5697);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('agethyn1h@phpbb.com', 'Asiatic jackal', 7410);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('agethyn1h@phpbb.com', 'Whale, killer', 9755);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('agethyn1h@phpbb.com', 'Red-winged blackbird', 9872);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('agethyn1h@phpbb.com', 'Galapagos penguin', 9424);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('agethyn1h@phpbb.com', 'Cobra, egyptian', 9236);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('goutibridge1i@stumbleupon.com', 'Vulture, griffon', 7685);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('goutibridge1i@stumbleupon.com', 'Savannah deer (unidentified)', 8612);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('goutibridge1i@stumbleupon.com', 'Gull, lava', 8605);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('goutibridge1i@stumbleupon.com', 'Asiatic jackal', 9400);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('goutibridge1i@stumbleupon.com', 'Bohor reedbuck', 9832);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('goutibridge1i@stumbleupon.com', 'Whale, killer', 9329);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('goutibridge1i@stumbleupon.com', 'Red-winged blackbird', 8816);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('goutibridge1i@stumbleupon.com', 'Monkey, red howler', 7011);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('goutibridge1i@stumbleupon.com', 'Cobra, egyptian', 7640);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fcomelini1j@sfgate.com', 'Vulture, griffon', 6829);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fcomelini1j@sfgate.com', 'Savannah deer (unidentified)', 9688);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fcomelini1j@sfgate.com', 'Red-winged blackbird', 8898);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fcomelini1j@sfgate.com', 'Monkey, red howler', 5394);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fcomelini1j@sfgate.com', 'Cobra, egyptian', 8957);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('scasperri1k@msn.com', 'Vulture, griffon', 8601);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('scasperri1k@msn.com', 'Savannah deer (unidentified)', 8191);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('scasperri1k@msn.com', 'Gull, lava', 9450);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('scasperri1k@msn.com', 'Asiatic jackal', 9217);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('scasperri1k@msn.com', 'Whale, killer', 6202);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('scasperri1k@msn.com', 'Red-winged blackbird', 8684);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('scasperri1k@msn.com', 'Monkey, red howler', 6841);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('scasperri1k@msn.com', 'Cobra, egyptian', 8850);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('rmerriton1l@ted.com', 'Vulture, griffon', 7222);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('rmerriton1l@ted.com', 'Gull, lava', 7394);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('rmerriton1l@ted.com', 'Asiatic jackal', 6894);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('rmerriton1l@ted.com', 'Whale, killer', 8298);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('rmerriton1l@ted.com', 'Red-winged blackbird', 8917);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('rmerriton1l@ted.com', 'Monkey, red howler', 6680);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('llowing1m@washington.edu', 'Vulture, griffon', 8294);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('llowing1m@washington.edu', 'Savannah deer (unidentified)', 8364);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('llowing1m@washington.edu', 'Gull, lava', 8764);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('llowing1m@washington.edu', 'Asiatic jackal', 8353);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('llowing1m@washington.edu', 'Bohor reedbuck', 9673);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('llowing1m@washington.edu', 'Whale, killer', 8469);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('llowing1m@washington.edu', 'Red-winged blackbird', 9357);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('llowing1m@washington.edu', 'Monkey, red howler', 6132);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('llowing1m@washington.edu', 'Cobra, egyptian', 9359);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gblackham1n@bigcartel.com', 'Vulture, griffon', 6351);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gblackham1n@bigcartel.com', 'Savannah deer (unidentified)', 8879);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gblackham1n@bigcartel.com', 'Asiatic jackal', 9194);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gblackham1n@bigcartel.com', 'Whale, killer', 7596);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gblackham1n@bigcartel.com', 'Red-winged blackbird', 8790);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gblackham1n@bigcartel.com', 'Monkey, red howler', 7984);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cross1o@goo.ne.jp', 'Vulture, griffon', 6210);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cross1o@goo.ne.jp', 'Savannah deer (unidentified)', 9074);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cross1o@goo.ne.jp', 'Gull, lava', 8529);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cross1o@goo.ne.jp', 'Bohor reedbuck', 9494);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cross1o@goo.ne.jp', 'Whale, killer', 8996);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cross1o@goo.ne.jp', 'Monkey, red howler', 5796);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('auttridge1p@myspace.com', 'Gull, lava', 8774);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('auttridge1p@myspace.com', 'Whale, killer', 7105);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('auttridge1p@myspace.com', 'Red-winged blackbird', 9356);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('auttridge1p@myspace.com', 'Monkey, red howler', 6313);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('auttridge1p@myspace.com', 'Cobra, egyptian', 7886);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dstuttard1q@creativecommons.org', 'Vulture, griffon', 5824);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dstuttard1q@creativecommons.org', 'Savannah deer (unidentified)', 8999);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dstuttard1q@creativecommons.org', 'Gull, lava', 8511);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dstuttard1q@creativecommons.org', 'Asiatic jackal', 9053);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dstuttard1q@creativecommons.org', 'Red-winged blackbird', 7949);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dstuttard1q@creativecommons.org', 'Monkey, red howler', 5362);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gmacvicar1r@senate.gov', 'Vulture, griffon', 8463);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gmacvicar1r@senate.gov', 'Savannah deer (unidentified)', 8625);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gmacvicar1r@senate.gov', 'Whale, killer', 8947);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gmacvicar1r@senate.gov', 'Monkey, red howler', 6625);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('deastup1s@nymag.com', 'Savannah deer (unidentified)', 8678);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('deastup1s@nymag.com', 'Gull, lava', 7311);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('deastup1s@nymag.com', 'Bohor reedbuck', 9361);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('deastup1s@nymag.com', 'Whale, killer', 9853);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('deastup1s@nymag.com', 'Monkey, red howler', 8214);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('awhorall1t@pen.io', 'Vulture, griffon', 7916);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('awhorall1t@pen.io', 'Savannah deer (unidentified)', 7470);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('awhorall1t@pen.io', 'Gull, lava', 8447);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('awhorall1t@pen.io', 'Asiatic jackal', 9295);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('awhorall1t@pen.io', 'Whale, killer', 7507);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('awhorall1t@pen.io', 'Monkey, red howler', 8117);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('bkinnin1u@dion.ne.jp', 'Vulture, griffon', 6555);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('bkinnin1u@dion.ne.jp', 'Savannah deer (unidentified)', 7584);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('bkinnin1u@dion.ne.jp', 'Gull, lava', 7104);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('bkinnin1u@dion.ne.jp', 'Asiatic jackal', 8428);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('bkinnin1u@dion.ne.jp', 'Whale, killer', 9014);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('bkinnin1u@dion.ne.jp', 'Red-winged blackbird', 8613);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('bkinnin1u@dion.ne.jp', 'Monkey, red howler', 7269);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cfifoot1v@europa.eu', 'Vulture, griffon', 7151);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cfifoot1v@europa.eu', 'Asiatic jackal', 8266);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cfifoot1v@europa.eu', 'Whale, killer', 7179);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cfifoot1v@europa.eu', 'Monkey, red howler', 6742);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('cfifoot1v@europa.eu', 'Cobra, egyptian', 8044);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('eraycroft1w@sitemeter.com', 'Vulture, griffon', 6045);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('eraycroft1w@sitemeter.com', 'Savannah deer (unidentified)', 9525);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('eraycroft1w@sitemeter.com', 'Asiatic jackal', 8570);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('eraycroft1w@sitemeter.com', 'Whale, killer', 9839);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('eraycroft1w@sitemeter.com', 'Red-winged blackbird', 9040);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('eraycroft1w@sitemeter.com', 'Monkey, red howler', 7667);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('eraycroft1w@sitemeter.com', 'Cobra, egyptian', 7615);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('plannen1x@mediafire.com', 'Vulture, griffon', 6737);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('plannen1x@mediafire.com', 'Savannah deer (unidentified)', 8272);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('plannen1x@mediafire.com', 'Gull, lava', 8785);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('plannen1x@mediafire.com', 'Bohor reedbuck', 9161);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('plannen1x@mediafire.com', 'Whale, killer', 8933);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('plannen1x@mediafire.com', 'Monkey, red howler', 9015);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('plannen1x@mediafire.com', 'Galapagos penguin', 8283);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('pgebuhr1y@reuters.com', 'Vulture, griffon', 9107);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('pgebuhr1y@reuters.com', 'Savannah deer (unidentified)', 7562);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('pgebuhr1y@reuters.com', 'Asiatic jackal', 9108);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('pgebuhr1y@reuters.com', 'Monkey, red howler', 5961);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('pgebuhr1y@reuters.com', 'Cobra, egyptian', 8343);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('jlockitt1z@java.com', 'Vulture, griffon', 6970);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('jlockitt1z@java.com', 'Gull, lava', 7358);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('jlockitt1z@java.com', 'Asiatic jackal', 9322);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('jlockitt1z@java.com', 'Whale, killer', 6798);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('jlockitt1z@java.com', 'Monkey, red howler', 8950);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dgriffin20@hugedomains.com', 'Vulture, griffon', 9503);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dgriffin20@hugedomains.com', 'Bohor reedbuck', 8925);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dgriffin20@hugedomains.com', 'Whale, killer', 8967);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dgriffin20@hugedomains.com', 'Monkey, red howler', 6618);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gofallone21@typepad.com', 'Vulture, griffon', 7902);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gofallone21@typepad.com', 'Savannah deer (unidentified)', 8290);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gofallone21@typepad.com', 'Gull, lava', 9190);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gofallone21@typepad.com', 'Asiatic jackal', 8254);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gofallone21@typepad.com', 'Bohor reedbuck', 8773);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gofallone21@typepad.com', 'Whale, killer', 8291);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gofallone21@typepad.com', 'Monkey, red howler', 8060);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fmaudett22@moonfruit.com', 'Vulture, griffon', 8769);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fmaudett22@moonfruit.com', 'Savannah deer (unidentified)', 8402);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fmaudett22@moonfruit.com', 'Asiatic jackal', 6823);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fmaudett22@moonfruit.com', 'Bohor reedbuck', 8872);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fmaudett22@moonfruit.com', 'Whale, killer', 5992);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('fmaudett22@moonfruit.com', 'Galapagos penguin', 8514);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('msteffens23@paypal.com', 'Vulture, griffon', 8694);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('msteffens23@paypal.com', 'Savannah deer (unidentified)', 9199);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('msteffens23@paypal.com', 'Gull, lava', 7698);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('msteffens23@paypal.com', 'Bohor reedbuck', 9226);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('msteffens23@paypal.com', 'Whale, killer', 7712);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('msteffens23@paypal.com', 'Monkey, red howler', 6947);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('msteffens23@paypal.com', 'Galapagos penguin', 9468);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('msteffens23@paypal.com', 'Cobra, egyptian', 9151);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lvizard24@blinklist.com', 'Vulture, griffon', 6968);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lvizard24@blinklist.com', 'Savannah deer (unidentified)', 8339);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lvizard24@blinklist.com', 'Gull, lava', 9018);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lvizard24@blinklist.com', 'Whale, killer', 9146);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lvizard24@blinklist.com', 'Red-winged blackbird', 7791);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lvizard24@blinklist.com', 'Monkey, red howler', 5859);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lvizard24@blinklist.com', 'Cobra, egyptian', 8378);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gpalfreyman25@fema.gov', 'Vulture, griffon', 5578);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gpalfreyman25@fema.gov', 'Asiatic jackal', 9080);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gpalfreyman25@fema.gov', 'Whale, killer', 8999);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gpalfreyman25@fema.gov', 'Red-winged blackbird', 7837);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gpalfreyman25@fema.gov', 'Monkey, red howler', 8090);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gpalfreyman25@fema.gov', 'Cobra, egyptian', 8987);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('brevey26@over-blog.com', 'Vulture, griffon', 9883);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('brevey26@over-blog.com', 'Savannah deer (unidentified)', 8878);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('brevey26@over-blog.com', 'Gull, lava', 7876);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('brevey26@over-blog.com', 'Asiatic jackal', 6963);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('brevey26@over-blog.com', 'Bohor reedbuck', 9529);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('brevey26@over-blog.com', 'Whale, killer', 7902);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('brevey26@over-blog.com', 'Monkey, red howler', 7081);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('brevey26@over-blog.com', 'Cobra, egyptian', 9610);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('vstruan27@economist.com', 'Vulture, griffon', 6879);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('vstruan27@economist.com', 'Asiatic jackal', 8476);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('vstruan27@economist.com', 'Whale, killer', 7394);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('vstruan27@economist.com', 'Monkey, red howler', 9295);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('vstruan27@economist.com', 'Galapagos penguin', 9598);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('jwolters28@over-blog.com', 'Vulture, griffon', 6200);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('jwolters28@over-blog.com', 'Gull, lava', 7673);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('jwolters28@over-blog.com', 'Asiatic jackal', 7025);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('jwolters28@over-blog.com', 'Whale, killer', 6886);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('jwolters28@over-blog.com', 'Monkey, red howler', 5904);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('jwolters28@over-blog.com', 'Cobra, egyptian', 8127);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lhedylstone29@nhs.uk', 'Vulture, griffon', 9826);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lhedylstone29@nhs.uk', 'Savannah deer (unidentified)', 7458);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lhedylstone29@nhs.uk', 'Asiatic jackal', 8880);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lhedylstone29@nhs.uk', 'Bohor reedbuck', 9245);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lhedylstone29@nhs.uk', 'Whale, killer', 9701);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lhedylstone29@nhs.uk', 'Red-winged blackbird', 8593);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lhedylstone29@nhs.uk', 'Monkey, red howler', 9802);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lhedylstone29@nhs.uk', 'Galapagos penguin', 8401);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lhedylstone29@nhs.uk', 'Cobra, egyptian', 8926);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lverne2a@vimeo.com', 'Vulture, griffon', 9321);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lverne2a@vimeo.com', 'Gull, lava', 7500);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lverne2a@vimeo.com', 'Asiatic jackal', 8593);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lverne2a@vimeo.com', 'Monkey, red howler', 7987);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lverne2a@vimeo.com', 'Cobra, egyptian', 7985);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('jbiggerstaff2b@mit.edu', 'Vulture, griffon', 9928);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('jbiggerstaff2b@mit.edu', 'Savannah deer (unidentified)', 7477);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('jbiggerstaff2b@mit.edu', 'Gull, lava', 8134);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('jbiggerstaff2b@mit.edu', 'Asiatic jackal', 9171);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('jbiggerstaff2b@mit.edu', 'Whale, killer', 9431);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('jbiggerstaff2b@mit.edu', 'Monkey, red howler', 8181);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('jbiggerstaff2b@mit.edu', 'Cobra, egyptian', 9451);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('msancias2c@multiply.com', 'Vulture, griffon', 6719);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('msancias2c@multiply.com', 'Gull, lava', 8985);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('msancias2c@multiply.com', 'Asiatic jackal', 7121);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('msancias2c@multiply.com', 'Bohor reedbuck', 8875);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('msancias2c@multiply.com', 'Whale, killer', 9011);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('msancias2c@multiply.com', 'Red-winged blackbird', 7833);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('msancias2c@multiply.com', 'Monkey, red howler', 7311);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('msancias2c@multiply.com', 'Galapagos penguin', 9725);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('msancias2c@multiply.com', 'Cobra, egyptian', 9604);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('vscotts2d@sourceforge.net', 'Vulture, griffon', 9882);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('vscotts2d@sourceforge.net', 'Savannah deer (unidentified)', 9351);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('vscotts2d@sourceforge.net', 'Gull, lava', 8383);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('vscotts2d@sourceforge.net', 'Whale, killer', 6067);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('vscotts2d@sourceforge.net', 'Red-winged blackbird', 8754);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('vscotts2d@sourceforge.net', 'Monkey, red howler', 5880);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('hseniour2e@skype.com', 'Gull, lava', 8527);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('hseniour2e@skype.com', 'Asiatic jackal', 9444);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('hseniour2e@skype.com', 'Bohor reedbuck', 9888);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('hseniour2e@skype.com', 'Red-winged blackbird', 8850);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('hseniour2e@skype.com', 'Monkey, red howler', 5966);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('hseniour2e@skype.com', 'Cobra, egyptian', 8357);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('nscheffel2f@e-recht24.de', 'Vulture, griffon', 6702);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('nscheffel2f@e-recht24.de', 'Savannah deer (unidentified)', 7290);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('nscheffel2f@e-recht24.de', 'Gull, lava', 7222);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('nscheffel2f@e-recht24.de', 'Asiatic jackal', 6999);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('nscheffel2f@e-recht24.de', 'Whale, killer', 6130);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('nscheffel2f@e-recht24.de', 'Red-winged blackbird', 8395);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('nscheffel2f@e-recht24.de', 'Monkey, red howler', 7037);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('nscheffel2f@e-recht24.de', 'Galapagos penguin', 9088);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('garkin2g@ted.com', 'Vulture, griffon', 6710);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('garkin2g@ted.com', 'Monkey, red howler', 6875);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('garkin2g@ted.com', 'Galapagos penguin', 9692);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('geden2h@webs.com', 'Vulture, griffon', 6370);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('geden2h@webs.com', 'Savannah deer (unidentified)', 7934);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('geden2h@webs.com', 'Gull, lava', 7651);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('geden2h@webs.com', 'Bohor reedbuck', 9900);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('geden2h@webs.com', 'Whale, killer', 7243);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('geden2h@webs.com', 'Red-winged blackbird', 8429);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('geden2h@webs.com', 'Monkey, red howler', 5981);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('geden2h@webs.com', 'Galapagos penguin', 8788);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('geden2h@webs.com', 'Cobra, egyptian', 7944);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ajurewicz2i@theatlantic.com', 'Vulture, griffon', 8953);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ajurewicz2i@theatlantic.com', 'Asiatic jackal', 7514);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ajurewicz2i@theatlantic.com', 'Whale, killer', 9823);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ajurewicz2i@theatlantic.com', 'Red-winged blackbird', 8630);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ajurewicz2i@theatlantic.com', 'Monkey, red howler', 9177);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('iwarlock2j@github.io', 'Vulture, griffon', 8138);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('iwarlock2j@github.io', 'Gull, lava', 8999);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('iwarlock2j@github.io', 'Asiatic jackal', 8340);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('iwarlock2j@github.io', 'Bohor reedbuck', 9074);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('iwarlock2j@github.io', 'Red-winged blackbird', 9846);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('iwarlock2j@github.io', 'Monkey, red howler', 8492);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('iwarlock2j@github.io', 'Galapagos penguin', 8606);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('iwarlock2j@github.io', 'Cobra, egyptian', 8435);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lgreenhouse2k@technorati.com', 'Vulture, griffon', 8539);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lgreenhouse2k@technorati.com', 'Savannah deer (unidentified)', 7165);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lgreenhouse2k@technorati.com', 'Asiatic jackal', 9223);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lgreenhouse2k@technorati.com', 'Whale, killer', 6206);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('lgreenhouse2k@technorati.com', 'Monkey, red howler', 6860);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dheld2l@blogtalkradio.com', 'Vulture, griffon', 6482);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dheld2l@blogtalkradio.com', 'Savannah deer (unidentified)', 9958);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dheld2l@blogtalkradio.com', 'Gull, lava', 9079);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dheld2l@blogtalkradio.com', 'Asiatic jackal', 7420);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dheld2l@blogtalkradio.com', 'Monkey, red howler', 9618);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dheld2l@blogtalkradio.com', 'Galapagos penguin', 9978);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('dheld2l@blogtalkradio.com', 'Cobra, egyptian', 8980);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ekruse2m@bandcamp.com', 'Vulture, griffon', 9736);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ekruse2m@bandcamp.com', 'Savannah deer (unidentified)', 7674);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ekruse2m@bandcamp.com', 'Gull, lava', 9749);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ekruse2m@bandcamp.com', 'Asiatic jackal', 8256);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ekruse2m@bandcamp.com', 'Whale, killer', 8675);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ekruse2m@bandcamp.com', 'Red-winged blackbird', 9132);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ekruse2m@bandcamp.com', 'Monkey, red howler', 7478);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ekruse2m@bandcamp.com', 'Galapagos penguin', 8776);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gsugar2n@skyrock.com', 'Vulture, griffon', 7733);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gsugar2n@skyrock.com', 'Gull, lava', 9584);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gsugar2n@skyrock.com', 'Asiatic jackal', 9990);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gsugar2n@skyrock.com', 'Whale, killer', 9881);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gsugar2n@skyrock.com', 'Red-winged blackbird', 8797);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gsugar2n@skyrock.com', 'Monkey, red howler', 5627);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('gsugar2n@skyrock.com', 'Galapagos penguin', 9325);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('emeasures2o@creativecommons.org', 'Vulture, griffon', 8796);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('emeasures2o@creativecommons.org', 'Savannah deer (unidentified)', 9493);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('emeasures2o@creativecommons.org', 'Gull, lava', 9438);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('emeasures2o@creativecommons.org', 'Bohor reedbuck', 9229);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('emeasures2o@creativecommons.org', 'Whale, killer', 8071);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('emeasures2o@creativecommons.org', 'Red-winged blackbird', 9074);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('emeasures2o@creativecommons.org', 'Monkey, red howler', 7061);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('aseeks2p@yale.edu', 'Vulture, griffon', 6833);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('aseeks2p@yale.edu', 'Gull, lava', 9933);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('aseeks2p@yale.edu', 'Asiatic jackal', 7691);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('aseeks2p@yale.edu', 'Bohor reedbuck', 9961);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('aseeks2p@yale.edu', 'Whale, killer', 6159);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('aseeks2p@yale.edu', 'Monkey, red howler', 8198);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('aseeks2p@yale.edu', 'Galapagos penguin', 8384);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('aseeks2p@yale.edu', 'Cobra, egyptian', 9855);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ebillyard2q@amazonaws.com', 'Vulture, griffon', 5990);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ebillyard2q@amazonaws.com', 'Savannah deer (unidentified)', 8462);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ebillyard2q@amazonaws.com', 'Bohor reedbuck', 9316);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ebillyard2q@amazonaws.com', 'Whale, killer', 7005);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ebillyard2q@amazonaws.com', 'Monkey, red howler', 5925);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('ebillyard2q@amazonaws.com', 'Cobra, egyptian', 9704);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mjillings2r@geocities.com', 'Vulture, griffon', 8840);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mjillings2r@geocities.com', 'Gull, lava', 7987);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mjillings2r@geocities.com', 'Asiatic jackal', 9515);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mjillings2r@geocities.com', 'Red-winged blackbird', 9412);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mjillings2r@geocities.com', 'Monkey, red howler', 7623);
INSERT INTO public.daily_prices (caretaker, category, price) VALUES ('mjillings2r@geocities.com', 'Galapagos penguin', 9314);