INSERT INTO public.categories (name, parent) VALUES ('Fox, crab-eating', null);
INSERT INTO public.categories (name, parent) VALUES ('Superb starling', null);
INSERT INTO public.categories (name, parent) VALUES ('American black bear', null);
INSERT INTO public.categories (name, parent) VALUES ('Vine snake (unidentified)', null);
INSERT INTO public.categories (name, parent) VALUES ('Hyena, brown', null);
INSERT INTO public.categories (name, parent) VALUES ('Stanley bustard', null);
INSERT INTO public.categories (name, parent) VALUES ('Javan gold-spotted mongoose', null);
INSERT INTO public.categories (name, parent) VALUES ('Mouse, four-striped grass', null);
INSERT INTO public.categories (name, parent) VALUES ('Spectacled caiman', null);
INSERT INTO public.categories (name, parent) VALUES ('Painted stork', null);